// Copyright (c) 2026 dexpace and Omar Aljarrah.
// Licensed under the MIT License. See LICENSE in the repository root for details.

// Generates the conformance kit's requirement catalogue from appendix C (phase 8a, P8a-13).
//
//   dotnet run scripts/ci/requirement-catalog.cs            # write src/Dexpace.Sdk.Conformance/Requirements/RequirementCatalog.g.cs
//   dotnet run scripts/ci/requirement-catalog.cs -- --check # compare a fresh render with the checked-in file
//
// Run from the repository root. Appendix C (docs/product-spec/appendix-c-consolidated-normative-requirement-index.md) is the
// canonical list of every normative requirement; each row starts `| ID | LEVEL |`. The generated file holds one
// (ID, level) line per row, in appendix order, so it diffs cleanly when the appendix changes. `MUST NOT` is folded into
// Must (the same weight). The kit's `ConformanceWaiver` validates its requirement ID against this table, and a Unit test in
// Dexpace.Sdk.Conformance.Tests regenerates the table in memory from the appendix and compares, so an edit to the appendix
// without a regeneration fails the test run.
//
// Exit 0 on success (`--check`: the file is current), 1 when `--check` finds the file stale, 2 on a usage or input error.

#:property RestorePackagesWithLockFile=false
#:property PublishAot=false

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

const string Appendix = "docs/product-spec/appendix-c-consolidated-normative-requirement-index.md";
const string Output = "src/Dexpace.Sdk.Conformance/Requirements/RequirementCatalog.g.cs";

var check = args.Length == 1 && args[0] == "--check";
if (args.Length > 1 || (args.Length == 1 && !check))
{
    Console.Error.WriteLine("usage: requirement-catalog.cs [--check]");
    return 2;
}

if (!File.Exists(Appendix) || !Directory.Exists(Path.GetDirectoryName(Output)!))
{
    Console.Error.WriteLine($"requirement-catalog: run from the repository root ({Appendix} not found)");
    return 2;
}

var row = new Regex(@"^\| ([A-Z]+-\d+) \| (MUST NOT|MUST|SHOULD|MAY) \|", RegexOptions.CultureInvariant);
var rows = File.ReadLines(Appendix)
    .Select(line => row.Match(line))
    .Where(match => match.Success)
    .Select(match => (Id: match.Groups[1].Value, Level: match.Groups[2].Value == "SHOULD" ? "Should" : match.Groups[2].Value == "MAY" ? "May" : "Must"))
    .ToList();

var duplicates = rows.GroupBy(r => r.Id, StringComparer.Ordinal).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
if (rows.Count == 0 || duplicates.Count > 0)
{
    Console.Error.WriteLine($"requirement-catalog: {(rows.Count == 0 ? "no requirement rows found" : "duplicate IDs: " + string.Join(", ", duplicates))}");
    return 2;
}

var text = new StringBuilder()
    .Append("// <auto-generated>\n")
    .Append("// Generated by scripts/ci/requirement-catalog.cs from docs/product-spec/appendix-c-consolidated-normative-requirement-index.md.\n")
    .Append("// Do not edit: regenerate with `dotnet run scripts/ci/requirement-catalog.cs`.\n")
    .Append("// </auto-generated>\n")
    .Append("// Copyright (c) 2026 dexpace and Omar Aljarrah.\n")
    .Append("// Licensed under the MIT License. See LICENSE in the repository root for details.\n")
    .Append('\n')
    .Append("using System.Collections.Generic;\n")
    .Append('\n')
    .Append("namespace Dexpace.Sdk.Conformance;\n")
    .Append('\n')
    .Append("/// <summary>Every normative requirement of appendix C, in appendix order, with its level.</summary>\n")
    .Append("internal static class RequirementCatalog\n")
    .Append("{\n")
    .Append("    /// <summary>The ").Append(rows.Count).Append(" rows: requirement ID and level (`MUST NOT` is folded into Must).</summary>\n")
    .Append("    internal static IReadOnlyList<(string Id, RequirementLevel Level)> Rows { get; } =\n")
    .Append("    [\n");
foreach (var (id, level) in rows)
{
    text.Append("        (\"").Append(id).Append("\", RequirementLevel.").Append(level).Append("),\n");
}

text.Append("    ];\n").Append("}\n");
var fresh = text.ToString();

if (!check)
{
    File.WriteAllText(Output, fresh, new UTF8Encoding(false));
    Console.WriteLine($"requirement-catalog: wrote {rows.Count} rows to {Output}");
    return 0;
}

var current = File.Exists(Output) ? File.ReadAllText(Output) : string.Empty;
if (current == fresh)
{
    Console.WriteLine($"requirement-catalog: {Output} is current ({rows.Count} rows)");
    return 0;
}

var have = current.Split('\n').ToHashSet(StringComparer.Ordinal);
var want = fresh.Split('\n').ToHashSet(StringComparer.Ordinal);
Console.Error.WriteLine($"requirement-catalog: {Output} is stale: {want.Except(have).Count()} line(s) missing, {have.Except(want).Count()} line(s) obsolete. Run `dotnet run scripts/ci/requirement-catalog.cs` and commit the result.");
return 1;
